<?php
require __DIR__ . '/../inc/header.inc';

?>

<main class="shadow container">
    <div class="row">
        <div class="col-xs-12">
            <?php require __DIR__ . '/../inc/breadcrumbs.inc'; ?>
        </div>
    </div>
    <div class="col-xs-12">
        <h2>Accessibility Statement</h2>
        <p><strong>Our commitment to accessibility</strong></p>
        <p>Bence Rewards is working hard to ensure that our website is accessible to all of our customers.</p>
        <p><strong>Accessibility for Bence Rewards - Website Standards<br>
            </strong>We endeavour to comply with the World Wide Web Consortium Accessibility Guidelines and will
            continue to review and improve our website to meet the guidelines. We strive to achieve compliance at AA
            level and AAA where possible.<br>
            &nbsp;<br>
            The website will appear best on a monitor set at a screen resolution of 1024 x 768 pixels. We ensure that
            the navigation through our websites works in a consistent way.<br>
            The website has been designed to be as accessible as possible with the following parameters in mind:</p>
        <p><strong>Accessibility for Bence Rewards - Images are also ‘tagged’ with a description<br>
            </strong>We have appropriate alt tags for images and links to convey relevant information. We avoid the use
            of images containing text wherever possible. We provide equivalent text that supports what the image is
            trying to convey using alt tags.</p>
        <p><strong>Accessibility for Bence Rewards - Font/text sizes and how to change it in internet explorer<br>
            </strong>We aim to use a web font so that all text is easy to read. However, to enlarge text on the site,
            please follow these simple steps:&nbsp;<br>
            1. On the browser Tools menu select 'Internet Options'<br>
            2. On the General tab, select 'Accessibility'<br>
            3. Tick the 'Ignore font sizes specified on web pages' check box<br>
            4. Click on 'OK'<br>
            5. On the browser menu select 'view'<br>
            6. Click 'text size'<br>
            7. Choose the size of text</p>
        <p><strong>Accessibility for Bence Rewards - Approach to colour in internet explorer<br>
            </strong>We do not rely on colour as the only way of giving information. If you want to change text and/or
            colour on the site, please follow these simple steps:<br>
            1. On the browser Tools menu select 'Internet Options'<br>
            2. On the General tab, select 'Colour'<br>
            3. Deselect the 'Use Windows Colours' tick box<br>
            4. Select the box next to 'Text' and choose a colour<br>
            5. Click on 'OK'<br>
            6. Select the box next to 'Background' and choose a colour<br>
            7. Click on 'OK'</p>
        <p><strong>To change the colour of links displayed on a screen, please follow these simple steps</strong>:<br>
            1. On the browser Tools menu select 'Internet Options'&nbsp;<br>
            2. On the General tab, select 'Accessibility'&nbsp;<br>
            3. Click on 'Select ignore colours specified on Web pages' (should contain a tick) - Click 'OK'&nbsp;<br>
            4. Select 'General' tab and click on 'Colours'&nbsp;<br>
            5. Turn off the 'Use hover colours' tick box (should not contain a tick)&nbsp;<br>
            6. Select 'Visited' and choose the colour that suits you best, Click OK&nbsp;<br>
            7. Select 'Not Visited' and choose the colour that suits you best, Click OK&nbsp;<br>
            8. Select 'OK' for 'Colours'&nbsp;<br>
            9. Select 'OK' for 'Internet Options'</p>
        <p><strong>Accessibility for Bence Rewards Page structure/design/screen resolution/contrast<br>
            </strong>This website uses Cascading Style Sheets (CSS) to control all of the presentation and layout.
            Tables are only used for data presentation. To view each page in full screen format on the browser View menu
            select 'Full screen' or press F11.</p>
        <p><strong>Accessibility for Bence Rewards - Access Keys &amp; Navigation tools<br>
            </strong>Using the tab key on the keyboard will allow you to navigate through the different areas of the
            website</p>
        <p><strong>Accessibility for Bence Rewards - Downloads/PDF documents</strong>:<br>
            To open a PDF file you can either:<br>
            1. Download a program called Acrobat Reader and install it onto your computer. The program is available free
            of charge from the&nbsp;<a href="http://get.adobe.com/reader/" title="go to Adobe website" target="_blank">Adobe
                Acrobat site</a>.&nbsp; We provide these links for the user wherever we list PDF Documents.<br>
            2. Use an online PDF conversion tool. You can visit the Adobe Acrobat website, type in the address of a PDF
            file and get it to translate the file into a more readable format while you wait. Or you can email the
            address of the file (or the file itself) to Adobe, and they will email a translation back. These
            translations of the files may not be as clearly formatted as the original PDF file.<br>
            3. If you are having difficulties downloading a PDF then you may need to update your version of Adobe
            Reader. See 'Download Adobe Reader' to get the latest version of this software.</p>
        <p><strong>Feedback<br>
            </strong>We are always keen to improve the accessibility of this website. Therefore, we would like to
            receive feedback on your experience of using this website. Therefore, if you have any comments, have found
            this web site inaccessible in any way or have had any difficulties whilst using it please email&nbsp;<a
                href="mailto:info@bencerewards.co.uk">info@bencerewards.co.uk</a>&nbsp;with any queries or comments.</p>
        <p>&nbsp;</p>
    </div>

</main>

<?php require __DIR__ . '/../inc/footer.inc'; ?>
