<?php
require __DIR__ . '/../inc/header.inc';

?>

<main class="shadow container">
    <div class="row">
        <div class="col-xs-12">
            <?php require __DIR__ . '/../inc/breadcrumbs.inc'; ?>
        </div>
    </div>

    <div class="col-xs-12">
        <h2>Conditions of use</h2>
        <p><strong>CONDITIONS OF WEBSITE USE</strong></p>
        <p><strong>INFORMATION ABOUT US</strong></p>
        <p><a href="http://www.bencerewards.co.uk/">www.bencerewards.co.uk</a>&nbsp;is a website operated by Bence
            Rewards ("we" or “us”).</p>
        <p><strong>TERMS OF WEBSITE USE</strong></p>
        <p>These are the conditions of use of this website. Please read them carefully as by viewing and using this
            website you indicate your acceptance of them and your agreement to be bound by them. You can print these
            conditions if you would like to retain a copy.&nbsp; Our Privacy Policy sets out how we will process
            information about you and also forms part of these conditions. </p>
        <p>If you are a consumer, nothing in these conditions will affect your statutory rights and if any of these
            conditions is held to be illegal, invalid or unenforceable in law, then it shall be deleted from these
            conditions but the remaining conditions will survive and continue to be enforceable.</p>
        <p><strong>ACCESSING OUR WEBSITE</strong></p>
        <p>We reserve the right to revise this website or withdraw access to part or all of it at any time. We may also
            change these conditions from time to time so you should check back regularly as you will be bound by any
            changes from the next time you access the website.&nbsp;</p>
        <p>The material and information on this website is directed solely at and is to be used only by persons who
            access it from within the United Kingdom and these conditions are only available in English. The release,
            publication or distribution of the information contained on this website in jurisdictions outside the United
            Kingdom may be restricted by laws that apply in other jurisdictions.</p>
        <p><strong>ACCOUNT INFORMATION AND USER IDENTIFICATION<br>
            </strong>&nbsp;<br>
            Where applicable, it is your responsibility to ensure the confidentiality of your account, user
            identification, password or any other information provided as part of our security procedures.&nbsp; You
            agree to accept responsibility for all activities that occur using your account, user identification or
            password and acknowledge that we shall not be liable to any person for any loss or damage which may arise as
            a result of your failure to keep this information secure. Please let us know immediately if you believe that
            your password, user identification or any other information provided as part of our security procedures has
            become known to anyone else, or if this information is being, or is likely to be, used in an unauthorised
            manner.</p>
        <p>We reserve the right to disable any user identification, account or password, at any time, if in our opinion
            you have failed to comply with any of the provisions of these conditions of use.</p>
        <p><strong>RELIANCE ON INFORMATION ON THIS WEBSITE</strong></p>
        <p>Although&nbsp; we have taken reasonable care to ensure that the information on this website is accurate and
            up to date, you should not rely on it as it is provided on an ‘as is’ basis and for guidance only.&nbsp; We
            and our affiliated companies do not make any warranty of any kind (expressed or implied) as to, or accept
            liability for, (in each case to the extent permitted by law), the accuracy, completeness, currency or
            reliability of any information contained on this web site.</p>
        <p><strong>OUR LIABILITY</strong></p>
        <p>The material displayed on this web site is provided without any guarantee, condition or warranty and we
            accept no liability for:&nbsp;<br>
            (a)&nbsp;economic loss (examples of which are loss of revenues, data, profits, contracts, business or
            anticipated savings),<br>
            (b)&nbsp;business losses or expenses,<br>
            (c)&nbsp;loss of goodwill or reputation, or<br>
            (d)&nbsp;indirect loss or damage,</p>
        <p>that arises from your reliance on, or the use of, the website (except for any claim arising from any
            purchases you make which will be governed by our Terms and Conditions of Sale).</p>
        <p>However, we never restrict our liability in respect of fraudulent misrepresentation, death or personal injury
            caused by our negligence or any matter which it would be illegal for us to exclude, or try to, exclude our
            liability.&nbsp;</p>
        <p><strong>VIRUSES AND HACKING<br>
            </strong>&nbsp;<br>
            We cannot guarantee the speed or security of this website and we shall not be responsible for or liable to
            you for any loss or damage caused to your computer equipment, programs or data arising as a result of the
            presence of any viruses, electronic bugs, Trojan horses or other technologically harmful material that may
            infect your computer due to the use of this website.&nbsp;</p>
        <p><strong>LINKS FROM OUR WEBSITE</strong></p>
        <p>Where this website contains links to other websites or resources from other third parties they are provided
            for your convenience only.&nbsp; We and our affiliate companies have no control over the content of those
            sites or resources and we accept no responsibility for them or for any loss or damage that may arise from
            your use of them.</p>
        <p><strong>COPYRIGHT AND TRADEMARKS<br>
            </strong>&nbsp;<br>
            The copyright in all website design, text, graphics, the selection and arrangement thereof, and all software
            compilations, underlying source code, software (including applets) and all other materials on this website
            belongs to us, our affiliates and our suppliers.</p>
        <p>You may download and print extracts from this website if you want to keep a copy or for your administrative
            purposes provided that you do not modify any material and you retain the copyright notice and provided that
            you do not make commercial use or gain from the website or any of its content.&nbsp; Any other use of
            material on this website is strictly prohibited without our prior written consent.&nbsp;&nbsp;</p>
        <p>All brand names used in the website are trade marks or trade names of their respective holders. Your use of
            any of these names or titles may constitute an infringement of the holders' rights.</p>
        <p><strong>JURISDICTION AND APPLICABLE LAW</strong></p>
        <p>This website, all its content and any contract brought into being as a result of its use shall be governed by
            and construed in accordance with English law. By using this website you agree to submit to the exclusive
            jurisdiction of the English courts.</p>
        <p>&nbsp;</p>
    </div>

</main>

<?php require __DIR__ . '/../inc/footer.inc'; ?>
