<?php
require __DIR__ . '/../inc/header.inc';

?>

<main class="shadow container">
    <div class="row">
        <div class="col-xs-12">
            <?php require __DIR__ . '/../inc/breadcrumbs.inc'; ?>
        </div>
    </div>

    <div>
        <h3>Got a query?</h3>
        <p>Please contact us with any queries or problems you may be experiencing, you can email us at <a href="mailto:info@bencerewards.co.uk">info@bencerewards.co.uk</a>.</p>
        <h3>Prefer to call?</h3>
        <p>If you prefer to call us, you are welcome to phone us on <strong>0117 9527741</strong>.</p>
        <h3>Address</h3>
        <p></p><strong>George Bence & Sons (Cheltenham) Ltd</strong>
        <br>
        George Bence & Sons (Cheltenham) Ltd, Registered Office<br>
        43 Fairview Road<br>
        Cheltenham<br>
        GL52 2EJ</p>
    </div>

</main>

<?php require __DIR__ . '/../inc/footer.inc'; ?>
