<?php
require __DIR__ . '/../inc/header.inc';

?>

<main class="shadow container">
    <div class="row">
        <div class="col-xs-12">
            <?php require __DIR__ . '/../inc/breadcrumbs.inc'; ?>
        </div>
    </div>

    <div class="col-xs-12">
        <h2>Privacy Policy</h2>
        <p>Bence Rewards ("<strong>we</strong>" or "<strong>us</strong>") are committed to protecting your privacy and we comply with the data protection laws applicable to the United Kingdom. This Privacy Policy explains how we use any information we collect about you and forms part of our Conditions of Use.</p>
        <p><strong>WHAT INFORMATION DO WE COLLECT ABOUT YOU?</strong></p>
        <p>We will collect information about you when you open an account, register with this website, place an order for products or services, request further information from us or if you wish to contact your local branch. The type of information we may collect includes your name, postal address, job title, e-mail address and telephone number so that we can contact you accordingly.</p>
        <p>When you enter a competition or promotional feature, we may also ask for your name, postal address, e-mail address and telephone number so we can administer the competition and notify winners.</p>
        <p>We may also obtain information about your usage of this website using Cookies.</p>
        <p>Separate terms and conditions may apply when you open an account or if you decide to participate in a competition so please make sure that you read these at the relevant time.</p>
        <p><strong>HOW DO WE USE THE INFORMATION WE COLLECT ABOUT YOU?</strong></p>
        <p>We may use the information provided by you:</p>
        <p>• to process your order or manage your account (if applicable),&nbsp;<br>
            • to contact you for your views on our services,&nbsp;<br>
            • to notify you about important changes or developments to our site or services,&nbsp;<br>
            • to provide a more personalised online experience,<br>
            • for record keeping purposes,<br>
            • to keep you informed about our products and services that we offer. If you agree, we may also pass your information to other companies in the Group so that they keep you informed about the products or services which they offer. For more information see the paragraph below, and&nbsp;<br>
            • for market research purposes, on an anonymous basis to track activity on our site, to publish trends and/or to improve usefulness and content,</p>
        <p>We only retain your information for a limited period in order to respond to your query, provide you with the information you require or to send you updates on our products and services for as long as you indicate that you are happy for us to do so. We are required to keep some records for a longer period of time to meet our legal obligations.</p>
        <p><strong>KEEPING YOU INFORMED</strong></p>
        <p>If you have bought or enquired about our products or services previously, we may also use the information we collect to let you know about our other products and services which may be of interest to you and to keep you updated with information about promotional offers and what is coming soon at Bence Rewards. If you agree, we would also like to send you information about the products and services offered by other companies in the Group.</p>
        <p>If the email address you have provided to us is a corporate email address, we may contact you at any time to let you know about our products and services.</p>
        <p>However, you will be able to let us know if you no longer want to receive material from us each time that you receive a communication by following the link to unsubscribe.</p>
        <p><strong>DISCLOSING YOUR DATA</strong></p>
        <p>We never make your personal details available to companies outside of the Bence Rewards group for marketing purposes and will only disclose your personal details to other companies within the Bence Rewards group if you have agreed to us doing so.</p>
        <p>However, we may use other companies to provide services to you on our behalf. These services may include but are not limited to answering your questions about products or services, sending postal mail and e-mails and analysing data. We will only provide those companies with the information they need to deliver the service we have engaged them for and they are prohibited from using that information for any other purpose.</p>
        <p>We may have to disclose your information by law or because a court or the police or other law enforcement agency has asked us for it. In the event that a majority of our shares were bought by another company or we transferred a substantial amount of our assets to another company, we would disclose your personal information to that purchaser.</p>
        <p><strong>HOW IS YOUR INFORMATION PROTECTED?</strong></p>
        <p>We take protection of your information seriously and have appropriate physical and technological security measures in place to keep it safe. Internally, we restrict access to personal information. Only employees who need the information in order to do their jobs have access to it. We never transfer your data outside of the UK.</p>
        <p><strong>COOKIES</strong></p>
        <p><a href="/cookies">Cookies</a> are small files that a website places on your hard disk to enable additional features of the website to work. Use of cookies is an industry standard and many websites use them and most internet browsers automatically accept cookies.</p>
        <p>The law relating to the use of <a href="/cookies">cookies</a> changed in May 2011. Website operators are now required to provide clear information in relation to the <a href="/cookies">cookies </a>operating on their site and to also obtain the user’s consent before setting a <a href="/cookies">cookie</a> on their computer or handheld device.</p>
        <p>Further information is set out below in relation to the cookies which operate on this website and we are currently reviewing our systems and procedures to establish the best way of obtaining consent to the setting of a <a href="/cookies">cookie</a> on a user’s computer or handheld device.</p>
        <p>Our<a href="/cookies"> cookies </a>do not contain any personally identifying information but they do enable us to provide a more user-friendly experience. We do not use <a href="/cookies">cookies</a> to gather personal information such as a person's name or e-mail address. However, in order to track usage on our website, we may use <a href="/cookies">cookies</a> to identify repeat visitors to the website and to determine the path visitors take on our site. Any information gathered by the use of cookies is compiled on an aggregate and anonymous basis. To specifically find out which cookies we use on the Bence Rewards website you can go to the cookies page.</p>
        <p>&nbsp;</p>
    </div>

</main>

<?php require __DIR__ . '/../inc/footer.inc'; ?>
