<?php
require __DIR__ . '/../inc/header.inc';

?>

<main class="shadow container">
    <div class="row">
        <div class="col-xs-12">
            <?php require __DIR__ . '/../inc/breadcrumbs.inc'; ?>
        </div>
    </div>

    <div class="col-xs-12">
        <h2>Terms and Conditions</h2>
    </div>
    <div class="col-xs-12">
        <ol>
            <li>By completing the online registration form, you agree to be bound by the terms and conditions contained
                below.<br>
            </li>
            <li>The Bence South &amp; South West Double Tier Promotion 2015 commences on 1 st April 2015 and ends on 30
                th September 2015 (“Promotional Period”).<br>
            </li>
            <li>The promotion is only open to existing Bence Trade Account who are invited by Bence to register for the
                reward scheme (“Participants”). This promotion excludes all other Trade Account
            </li>
            holders of subsidiary companies of Travis Perkins plc and all Bence and Travis Perkins plc current and
            previous employees or public sector and housing association employees.<br>
            <li>The promotion is not open to all employees of any agencies or event suppliers or their families or
                agents or any other person officially connected with the promotion.<br>
            </li>
            <li>In order to participate in the promotion, Participants must first register by email –
                info@bencerewards.co.uk. No third party or joint registrations will be accepted.
            </li>
            <li>All Participants in the Bence South &amp; South West Double Tier Promotion 2015 must be resident in the
                UK and aged 18 or over.<br>
            </li>
            <li>Each Participant will have an individual order target to achieve for each tier level in the Promotion,
                over the Promotional Period. If the order target is achieved at any tier, the Participant will
                be eligible to participate in a “reward” from that tier (which is detailed more fully on paragraph 9).
                Only transactions fully paid up to standard trading terms during the Promotional Period will
                count towards the order target. A ll targets are excluding VAT. The Bence Branch Managers decision as to
                which orders will and will not count towards the order target shall be binding on
                the Participant and final.<br>
            </li>
            <li>Participants who do not achieve their order target are not eligible for an incentive or any part
                thereof, or any cash equivalent.<br>
            </li>
            <li>If it is confirmed by Bence that the Participant has achieved the order target during the Promotional
                Period, the Participant shall receive a letter of congratulations, confirming target achieved
                and details of the chosen event as shown in the South &amp; South West promotional brochure (of which
                the Participant has been given a copy).<br>
            </li>
            <li>Bence will try to allocate successful Participants to their choice of reward, as rewards are subject to
                availability this cannot be guaranteed. The rewards are subject to availability and will be
                allocated on a strictly ‘first come, first served’ basis once the set order target has been achieved.
                Should your first choice of event not be possible then every effort will be made to provide
                a mutually agreeable alternative. If agreement cannot be reached, Bence will act in accordance with
                clause 22.<br>
            </li>
            <li>The reward cannot be transferred, sold or in any way traded.<br>
            </li>
            <li>For the avoidance of doubt, reward earned by a company holding a Trade Account shall be for the benefit
                of the company and not individuals.<br>
            </li>
            <li>Those participating in a motorbased
                event (cars/bikes, on/off road, official track ) must hold a current full and valid UK driving
                licence.<br>
            </li>
            <li>Unless clearly stated expenses incurred during or as a result of participation in any of the reward are
                not included in the Promotion and shall be for the Participant’s own account.<br>
            </li>
            <li>Participants will be responsible for arranging and providing their own means of transportation to and
                from the commencement &amp; completion points of the reward.<br>
            </li>
            <li>Rewards shall only be permitted to go ahead if, customer account has adhered to standard trading terms
                and conditions with no outstanding invoices attributable to the Promotional
                Period, or whose account has been suspended due to nonpayment/
                legal issues. If any products included in your order total are returned or refunded (in part or in full)
                these purchases (or
                part thereof) will be discounted from the promotion, except for occasions when the product is faulty or
                damaged through no fault of the Participant. This does not affect your statutory
                rights.<br>
            </li>
            <li>Bence will confirm fully validated account detail to successful participants to confirm their reward
                during October 2015. Bence’s decision is final as to the reward allocated to the successful
                Participant.<br>
            </li>
            <li>Reward dates are subject to availability and will be confirmed in due course, all rewards must be booked
                on or before 31 st December 2016.<br>
            </li>
            <li>All persons attending the reward agree to accept the waiver of responsibility by signing the booking
                form prior to registering for the Promotion. Bence accepts no responsibility for any loss or
                damage caused by negligence of Bence, its servants or agents out of or in connection with this Promotion
                except where caused by wilful neglect of Bence, its employees or agents. Nothing in
                the clause is deemed to exclude or restrict liability for death or personal injury resulting from the
                negligence of Bence, its employees or agents.<br>
            </li>
            <li>Obtaining insurance is at the Participants discretion and is for their own account. Bence shall not be
                responsible for any insurance.<br>
            </li>
            <li>Bence will not accept liability for change to the venue /events due to decisions by the event organisers
                or suppliers. Bence reserves the right to change the venue and/or events within the
                Bence South &amp; South West Double Tier Promotion 2015 with notification, and will provide an
                alternative venue and/or events of equal value. In the event that this is not possible, Bence
                reserves the right to substitute the event for a similar gift or a similar value.<br>
            </li>
            <li>No cash equivalent shall be provided for rewards. Bence accepts no responsibility for any loss incurred
                as a result of these changes. Participation in the reward is subject to event
                organisers’ or suppliers’ Terms and Conditions. Copies of suppliers’ Terms and Conditions are available
                from Bence upon request.<br>
            </li>
            <li>Rewards may be subject to tax and National Insurance. Any tax implications remain with the Participant.
                For further information please contact your nearest Inland Revenue Office. Bence
                will not be liable for any such tax and/or national insurance.
            </li>
            <li>Any rewards that individuals from your company receive are received purely in the capacity of an agent,
                acting on behalf of your company. Any decision entitling individuals to be the
                recipient of rewards rests with your company and not with Bence.
            </li>
            <li>In the event of any dispute, the decision of Bence and its appointed representatives is final in all
                matters and no correspondence shall be entered into.
            </li>
            <li>This offer may not be used in conjunction with any other offer. This offer is nontransferable.</li>
            <li>Bence reserves the right to amend or withdraw this Rewards Promotion in whole or in part without prior
                notice or compensation.
            </li>
            <li>General enquiries should be addressed to: info@bencerewards.
                co.uk or www.bencerewards.
                co.uk/contact
            </li>
            <li>By participating in the rewards Participants are deemed to give their consent to appear in publicity
                material or other events relating to the rewards Promotion. Participants may be asked to
                participate in future publicity or PR activities, which may involve taking photographs.
            </li>
        </ol>
    </div>

</main>

<?php require __DIR__ . '/../inc/footer.inc'; ?>
