<?php require __DIR__ . '/inc/header.inc'; ?>

<main class="container">
    <div class="row no-pad">
        <div class="col-xs-12">
            <?php /*<div class="home-feature" style="background-image: url('<?php echo $data['sliderPromo']['thumb']; ?>');">
                <h3><?php echo $data['sliderPromo']['title']; ?></h3>
            </div> */ ?>
            <?php require 'inc/carousel.inc'; ?>
        </div>
    </div>
    <div class="row no-pad">
        <div class="col-md-4">
            <a href="/account/tier/1/">
                <div class="feature-box" style="background-image: url('/img/rewards/2019/maze-grill.jpg');">
                    <h3>The Cherokee</h3>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="/account/tier/2/">
                <div class="feature-box" style="background-image: url('/img/rewards/2019/helicopter.jpg');">
                    <h3>The Cheyenne</h3>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="/account/tier/3/">
                <div class="feature-box" style="background-image: url('/img/rewards/2019/boat-and-sea.jpg');">
                    <h3>The Chinook</h3>
                </div>
            </a>
        </div>
    </div>
    <div class="row no-pad">
        <div class="col-xs-12">
            <div class="slightly-centred-div ipsum">
                <p><strong>Welcome</strong></p>
                "At Bences our aim is to supply quality building materials at affordable costs with a first class
                service
                to enable you to add value to your business.
                <br>
                <br>
                To encourage loyalty as an independent local company ourselves,
                we would like to introduce the following incentives from our new rewards scheme.”
                <br>
                <br>
                Please remember spend is valid across all four of our businesses.
                <br>
                Paul Bence, Managing Director
            </div>
        </div>
    </div>
</main>

<?php require __DIR__ . '/inc/footer.inc'; ?>

