<?php require __DIR__ . '/inc/header.inc'; ?>

<main class="shadow container">
    <div class="row">
        <div class="col-xs-12">
            <?php require __DIR__ . '/inc/breadcrumbs.inc'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h2>Login</h2>
            <?php
            if (isset($data['login']) && $data['login'] == false) {
                echo '<p class="text-danger">Incorrect username or password</p>';
            }
            ?>
            <form action="/login" method="POST">
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" name="email" class="form-control" id="email">
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="remember" value="true">
                        Remember Me
                    </label>
                </div>
                <button type="submit" class="btn btn-default">Login</button>
            </form>
        </div>
        <div class="col-md-6">
            <h2>Forgotten Your Password?</h2>
            <p>Forgotten your password? <a href="login/reset">Click here to request a password reset email</a>.</p>
        </div>

        <div class="col-md-6">
            <h2>Still can't log in?</h2>
            <p>If your still unable to log in to your account, please contact us at <a href="mailto:">info@bencerewards.co.uk</a>.
            </p>
        </div>
    </div>
</main>

<?php require __DIR__ . '/inc/footer.inc'; ?>
