<?php
require __DIR__ . '/inc/db_conn.inc';
require __DIR__ . '/inc/header.inc';

$query = $con->prepare(
        'SELECT
          id,
          subject,
          created,
          SUM(sent_successfully) AS successful,
          (COUNT(sent_successfully) - SUM(sent_successfully)) AS failed
        FROM email_log JOIN email_user_sent_status ON email_id = email_log.id
        GROUP BY id;');
$query->execute();

$notifications = $query->fetchAll(PDO::FETCH_ASSOC);

$i = 0;
$yes = 0;
$no = 0;
$total = 0;
?>
    <main class="shadow container">
        <div class="row">
            <div class="col-xs-12">
                <?php require __DIR__ . '/inc/breadcrumbs.inc'; ?>
            </div>
        </div>

        <div class="col-xs-12">

            <input id="searchInput" value="Filter By Subject"><i> (Tip: Case Sensitive)</i>
        </div>
        <div class="col-xs-12">
            <table class="table" id="users">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Subject</th>
                    <th>Date</th>
                    <th>Succeeded</th>
                    <th>Failed</th>
                </tr>
                </thead>
                <tbody id="fbody">
                <?php foreach ($notifications as $notification) {
                    ?>
                    <tr>
                        <td>
                            <a href="/notifications/<?php echo $notification['id']; ?>"><?php echo $notification['id']; ?></a>
                        </td>
                        <td>
                            <?php echo $notification['subject']; ?>
                        </td>
                        <td>
                            <?php echo $notification['created']; ?>
                        </td>
                        <td class="activated cell">
                            <?php echo $notification['successful']; ?>
                        </td>
                        <td class="inactive cell">
                            <?php echo $notification['failed']; ?>
                        </td>

                        <!--<td data-region="<?php //echo $notification['r_id']; ?>"><?php //echo $notification['r_name']; ?></td>-->
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>

        <script>
            $("#searchInput").keyup(function () {
                //split the current value of searchInput
                var data = this.value.split(" ");
                //create a jquery object of the rows
                var jo = $("#fbody").find("tr");
                if (this.value == "") {
                    jo.show();
                    return;
                }
                //hide all the rows
                jo.hide();

                //Recusively filter the jquery object to get results.
                jo.filter(function (i, v) {
                    var $t = $(this);
                    for (var d = 0; d < data.length; ++d) {
                        if ($t.is(":contains('" + data[ d ] + "')")) {
                            return true;
                        }
                    }
                    return false;
                })
                //show the rows that match.
                    .show();
            }).focus(function () {
                this.value = "";
                $(this).css({
                    "color": "black"
                });
                $(this).unbind('focus');
            }).css({
                "color": "#C0C0C0"
            });

        </script>

    </main>

<?php
require __DIR__ . '/inc/footer.inc';
