<footer>
    <div class="container">
        <div class="col-xs-12">
            <nav class="slightly-centred-div seperater">
                <a href="/contact">Contact Us</a>| <?php // <a href="/terms">Terms and Conditions</a> | ?>
                <a href="/privacy">Privacy Policy</a> | <a href="/access">Access Statement</a> |
                <a href="/conditions">Conditions of use</a> | <a href="#">Back to top</a>
            </nav>
            <div class="slightly-centred-div metadata seperater logos">
                <div class="col-sm-4 col-xs-12">
                    <a href="http://obsidian-interiors.co.uk" target="_blank"><img src="/img/obsidian-logo.jpg"></a>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <a href="http://bence.co.uk" target="_blank"><img src="/img/bence-logo.jpg"></a>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <a href="http://bence.co.uk" target="_blank"><img src="/img/bence-dec-logo.jpg"></a>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <a href="http://bence.co.uk" target="_blank"><img src="/img/bence-roofing-logo.jpg"></a>
                </div>

                <div class="col-xs-12">
                    <p class="text-center">Spend across the whole group is valid</p>
                </div>
            </div>
			<?php /*
            <div class="slightly-centred-div metadata">
                <div>&copy; <?php echo date('Y'); ?> Finders Keepers Ltd | Design by <a
                        href="http://www.finderskeepersuk.com">Finders Keepers Sports and Marketing Ltd</a></div>
            </div> */
			?>
        </div>
    </div>
</footer>
</body>
</html>